# Generated by Django 2.2.6 on 2019-11-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(name="user", options={}),
        migrations.AlterModelTable(name="user", table="USER"),
    ]
